# Generated by Django 2.0.6 on 2018-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Req_st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.TextField(max_length=1900)),
                ('sender', models.CharField(max_length=200)),
                ('date_up', models.DateField(auto_now_add=True)),
                ('sponser', models.CharField(blank=True, max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('req_spon', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
