# Generated by Django 2.1.1 on 2018-09-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20180907_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
