# Generated by Django 2.0.6 on 2018-09-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('birth_date', models.DateField(null=True)),
                ('number', models.CharField(max_length=12)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('img', models.FileField(upload_to='docs/')),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('up_date', models.DateField(auto_now_add=True)),
                ('type_user', models.CharField(default='student', max_length=50)),
                ('disabled', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
