# Generated by Django 2.0.6 on 2018-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.IntegerField(default=False),
        ),
    ]
