# Generated by Django 2.0.6 on 2018-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180924_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
