# Generated by Django 2.0.6 on 2018-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180924_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.CharField(choices=[('Baghdad', 'Baghdad'), ('Karbala', 'Karbala'), ('Deyala', 'Deyala'), ('basrah', 'basrah')], max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='stage',
            field=models.CharField(choices=[('First stage', 'First stage'), ('second stage', 'second stage'), ('third stage', 'third stage')], max_length=50),
        ),
    ]
