# Generated by Django 2.0.6 on 2018-10-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181023_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='number',
        ),
    ]
