# Generated by Django 2.0.6 on 2018-10-23 17:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_sponsor_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='number',
        ),
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='use +9647700000000', max_length=128),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='use +9647700000000', max_length=128),
        ),
    ]
